### ISSUE TITLE
no "dist" folder is found

### ISSUE THREAD

**Issue by walter426** [paulproteus/mdb-sqlite#1]
Could you add the "dist" folder with the .class files into this project like the formal release?

As I don't know how to compile the .class files from this github project.

**Comment by walter426** [comment]
Sorry, i know how to solve it now.
Just run "ant dist" in command prompt

**Comment by paulproteus** [comment]
Great! i'm glad that you were able to fix this.

Would you be willing to write some text in `README.md` in this project so that others can find that out, too?

More info on that:
- https://help.github.com/articles/create-a-repo/#commit-your-first-change
- http://programmers.stackexchange.com/questions/128712/what-is-a-markdown-formatted-readme-file-on-github
- https://yangsu.github.io/pull-request-tutorial/

I'll close this issue for now, but feel free to re-open it.
