### ISSUE TITLE
script doesn't work

### ISSUE THREAD

**Issue by barryrowlingson** [paulproteus/mdb-sqlite#2]
the run.sh script doesn't pass the args through - fix by adding $\* to the java run line:

java  -classpath "$CLASSPATH" com.plausiblelabs.mdb.Main $*

its a nice project, hope it can keep going...

**Comment by paulproteus** [comment]
Hi there!

I've been a little slow to maintain this project, but if you submit a pull request, I will review it. My perspective is that I know that I'm not going to be able to write code on this project reliably, so I prefer to grow the number of people who have contributed code, rather than contribute more code myself. I am willing to do code reviews and merge changes.

So - if you need help submitting a pull request, I am willing to invest time in working with you on learning that, including a video chat if you want. The best way to schedule time is to email asheesh@sandstorm.io and CC: clara.thorne@claralabs.com saying you want a 1 hour video chat, and Clara and I will schedule something.

Let me know what you think!

**Comment by barryrowlingson** [comment]
PR submitted....

**Comment by paulproteus** [comment]
Wow, thanks!

**Comment by paulproteus** [comment]
I'll close this since it is fixed now. :tada: to you @barryrowlingson
